/**
 * Configurações centrais do módulo de apresentações.
 */

var APRESENTACOES_CFG = Object.freeze({
  REGISTRY_KEYS: {
    PROCESSAMENTO: 'APRESENTACOES_PROCESSAMENTO',
    HISTORICO_PUBLICO: 'APRESENTACOES_HISTORICO_PUBLICO',
    MEMBERS: 'MEMBERS_ATUAIS',
    PROFS: 'PROFS_BASE',
    PASTA_RAIZ_APRESENTACOES: 'APRESENTACOES_PASTA_RAIZ',
    PASTA_UPLOAD_FOTOS: 'APRESENTACOES_UPLOAD_FOTOS'
  },

  STATUS_APRESENTACAO: {
    CONFIRMADA: 'Confirmada',
    APROVADA: 'Aprovada'
  },

  STATUS_ARQUIVO: {
    SOLICITADO: 'Solicitado',
    RECEBIDO: 'Recebido'
  },

  VALORES_SIM_NAO: {
    SIM: 'SIM',
    NAO: 'NÃO'
  },

  COBRANCA_TITULO_EIXO: {
    JANELA_DIAS_ANTES_MIN: 1,
    JANELA_DIAS_ANTES_MAX: 4
  },

  COBRANCA_ARQUIVO: {
    HORA_ENVIO_PADRAO: 22,
    MINUTO_ENVIO_PADRAO: 0,
    PRAZO_HORAS: 72
  }
});